[build]
  functions = "netlify/functions"

[functions]
  # Sertakan answerKey.json ke dalam bundle Lambda
  included_files = ["netlify/functions/answerKey.json"]

[dev]
  functions = "netlify/functions"
